name: event_360
description: Application Évènementielle

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  badges: ^2.0.3
  line_awesome_flutter: ^2.0.0
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0
  intl_phone_field: ^3.1.0
  pinput: ^2.2.16
  flutter_svg: ^1.1.6
  provider: ^5.0.0
  bottom_navy_bar: ^6.0.0
  curved_navigation_bar: ^1.0.3
  flutter_spinkit: ^5.1.0
  like_button: ^2.0.5
  share_plus: ^4.5.3
  ticket_material: ^0.3.1
  get: ^4.6.5


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/
    - assets/icons/
    - assets/profil/
 
  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/mulish/Mulish-Black.ttf
        - asset: assets/fonts/mulish/Mulish-Bold.ttf
          weight: 700
        - asset: assets/fonts/mulish/Mulish-Light.ttf
        - asset: assets/fonts/mulish/Mulish-ExtraBoldItalic.ttf
          weight: 300
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
